server:
  error:
    include-stacktrace: never

spring:
  datasource:
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}

    show-sql: false

    jpa:
      hibernate:
        ddl-auto: none


logging:
  level:
    ROOT: INFO