spring:
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    username: ""
    password: ""
    url: "jdbc:h2:./localDB"
    show-sql: true

  jpa:
    hibernate:
     ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true


logging:
  level:
    root: INFO
    web: DEBUG