server:
  port: ${PORT:5000}

base-url: /api

spring:
  application:
    name: project-5
  profiles:
    active: prod
  security:
    filter-order: 10

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

