server:
  error:
    include-stacktrace: never

spring:
    datasource:
      platform: postgres
      username: ${USERNAME}
      password: ${PASSWORD}
      url: jdbc:postgresql://${HOST}:${PORT}/${DB_NAME}
      driverClassName: org.postgresql.Driver

    jpa:
      show-sql: false

      hibernate:
        ddl-auto: validate


logging:
  level:
    ROOT: INFO