server:
  error:
    include-stacktrace: never

spring:
    datasource:
      username: ${USERNAME}
      password: ${PASSWORD}
      url: jdbc:postgres://${HOST}:${PORT}/${DB_NAME}

    jpa:
      show-sql: false

      hibernate:
        ddl-auto: none


logging:
  level:
    ROOT: INFO