package hexlet.code.controller;

import com.querydsl.core.types.Predicate;
import hexlet.code.dto.TaskDtoRequest;
import hexlet.code.model.Task;
import hexlet.code.service.TaskService;
import hexlet.code.service.UserService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.querydsl.binding.QuerydslPredicate;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

/**
 * Rest controller to process a request for an endpoint /tasks.
 * @author sobadxx
 */
@RestController
@RequestMapping(value = "${base-url}" + "/tasks")
public class TaskController {
    public static final String TASK_CONTROLLER_PATH = "/api/tasks";
    public static final String ID = "/{id}";
    @Autowired
    private TaskService taskService;
    @Autowired
    private UserService userService;

    /**
     * GET request handler on endpoint "api/tasks/{id}".
     *
     * @param id path variable from request
     * @return {@link Task} from {@link TaskService#getTask(Long)}
     */
    @Operation(summary = "Get task by ID")
    @ApiResponses(value = {
        @ApiResponse(responseCode = "200", description = "Task with that ID was found"),
    })
    @GetMapping(ID)
    public Task getTaskById(@PathVariable Long id) {
        return taskService.getTask(id);
    }

    /**
     * GET request handler on endpoint "api/tasks".
     *
     * @param predicate boolean predicate consisting of query parameters generated by querydsl
     * @return All entities {@link Task} from {@link TaskService#getFilteredTasks(Predicate)}
     */
    @Operation(summary = "Get a list of all tasks")
    @ApiResponses(value = {
        @ApiResponse(responseCode = "200", content =
            @Content(schema =
            @Schema(implementation = Task.class)))
    })
    @GetMapping("")
    public Iterable<Task> getFilteredTasks(@QuerydslPredicate(root = Task.class) Predicate predicate) {
        return taskService.getFilteredTasks(predicate);
    }

    /**
     * POST request handler on endpoint "api/tasks".
     *
     * @param taskDtoRequest JSON request body
     * @return Created {@link Task} from {@link TaskService#createTask(TaskDtoRequest)}
     */
    @Operation(summary = "Create a new task")
    @ApiResponse(responseCode = "201", description = "Task created")
    @PostMapping("")
    @ResponseStatus(HttpStatus.CREATED)
    public Task createTask(@RequestBody TaskDtoRequest taskDtoRequest) {
        return taskService.createTask(taskDtoRequest);
    }

    /**
     * PUT request handler on endpoint "api/tasks/{id}".
     *
     * @param taskDtoRequest JSON request body
     * @param id path variable from request
     * @return Created {@link Task} from {@link TaskService#updateTask(TaskDtoRequest, Long)}
     */
    @Operation(summary = "Update task by ID")
    @PutMapping(ID)
    public Task updateTask(@RequestBody TaskDtoRequest taskDtoRequest, @PathVariable Long id) {
        return taskService.updateTask(taskDtoRequest, id);
    }

    /**
     * DELETE request handler on endpoint "api/tasks/{id}".
     *
     * @param id path variable from request
     * @see TaskService#deleteTask(Long)
     */
    @Operation(summary = "Delete a task")
    @DeleteMapping(ID)
    public void deleteTask(@PathVariable Long id) {
        taskService.deleteTask(id);
    }
}
